version: "3.9"
services:
  singleton:
    build:
      context: .
      dockerfile: singleton.dockerfile
    ports:
      - "5000:5000"
  multiton:
    build:
      context: .
      dockerfile: multiton.dockerfile
    ports:
      - "8000:5000"
  alpine:
    build:
      context: .
      dockerfile: multiton-alpine.dockerfile
    ports:
      - "7000:5000"
